"use client";
import Head from "next/head";
import Image from "next/image";
import { getLocalStorage } from "@/lib/localStorage";
import useLine from "@/lib/hook/useLine";

export default function Home(props) {
  const { liffObject } = props;
  const status = getLocalStorage("status");
  const { login, logout } = useLine();

  if (status !== "inited") {
    return (
      <>
        <Head>
          <title>One Retail</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex flex-col justify-center items-center">
          <button onClick={login} className="bg-blue-500 text-white font-bold py-2 px-4 rounded">Login</button>
        </main>
        </>
    );
  }
  return (
    <>
      <Head>
        <title>One Retail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center">
        <button onClick={logout} className="bg-blue-500 text-white font-bold py-2 px-4 rounded">Logout</button>
      </main>
      </>
  );
}